# colorscheme
import =  ["~/.config/alacritty/ayu_dark.toml"]

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[shell]
program = "/usr/bin/fish"

[window.padding]
x = 5
y = 5
