theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.g]
# select lines https://github.com/helix-editor/helix/issues/1630#issuecomment-1511995639
l = ["collapse_selection", "extend_to_line_end"]
h = ["collapse_selection", "extend_to_line_start"]
s = ["collapse_selection", "select_mode", "goto_first_nonwhitespace", "exit_select_mode"]
  
[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal."space"]
f = "file_picker_in_current_buffer_directory"
q = ":buffer-close"
s = ":w"
