theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":w" # save file
C-q = ":q" # quit program
C-p = ":bp" # buffer next
C-n = ":bn" # buffer previous
C-o = ":o" # open a file
  
[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal."space"]
f = "file_picker_in_current_buffer_directory"
