theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":w" # ctrl-s saves file
C-q = ":q" # ctrl-q quits program

[keys.insert]
j = { h = "normal_mode" } # Maps `jh` to exit insert mode

[keys.normal."space"]
f = "file_picker_in_current_buffer_directory"
